pipeline {
    agent any
    stages {
        stage('Setup') {
            steps {
                sh """
                    mkdir newdir
                    sh newdir
                """
                //
            }
        }
    }
}