pipeline {
    agent any
    stages {
        stage('Setup') {
            steps {
                sh """
                    mkdir newdir2
                    cd newdir2
                """
                //
            }
        }
    }
}